# -*- coding: utf-8 -*-
"""Hashing_NLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11A3vJ0dySPOO9LqeLN_oyk3s2Mlq3IW3
"""

from sklearn.feature_extraction.text import HashingVectorizer
# list of text documents
text = ["The quick brown fox jumped over the lazy dog."]

vectorizer = HashingVectorizer(n_features=20)
vector = vectorizer.transform(text)

print(vector.shape)

print(vector.toarray())

