# -*- coding: utf-8 -*-
"""N_grams_NLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IuOmcjx-nfN5OLRKnkyhkdFxoWH7IecU
"""

import re

#Natural Language Processing, or NLP for short, n-grams are used for a variety of things. Some examples include auto 
#completion of sentences (such as the one we see in Gmail these days), auto spell check (yes, we can do that as well), and to a 
#certain extent, we can check for grammar in a given sentence.

def N_Grams(text,n): 
    # split sentences into tokens
    tokens=re.split("\\s+",text)
    ngrams=[] 
    # collect the n-grams
    for i in range(len(tokens)-n+1):
     temp=[tokens[j] for j in range(i,i+n)]
     ngrams.append(" ".join(temp)) 
    return ngrams

text1="the quick brown fox jumps the lazy dog";

N_Grams(text1,1)

N_Grams(text1,2)

N_Grams(text1,3)

