# -*- coding: utf-8 -*-
"""TF_IFD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kbJxL1gWFncjJoRTTIMRRi3T9TdDlHgy
"""

from sklearn.feature_extraction.text import CountVectorizer
# list of text documents
text = ["The car is driven on the road.","The truck is driven on the highway"]

# create the transform
vectorizer = CountVectorizer()

# tokenize and build vocab
vectorizer.fit(text)

# summarize
print(vectorizer.vocabulary_)

# encode document
newvector = vectorizer.transform(text)

# summarize encoded vector
print(newvector.toarray())

"""# TF - IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer
# list of text documents
text = ["The car is driven on the road.","The truck is driven on the highway"]

# create the transform
vectorizer = TfidfVectorizer()

# tokenize and build vocab
vectorizer.fit(text)

#Focus on IDF VALUES
print(vectorizer.idf_)

# summarize
print(vectorizer.vocabulary_)

